defaults:
  - optional random: ${modality}

_target_: envs.debug.random_env.RandomEnv

action_dim: 2
state_obs_dim: 3
pixels_img_size: ${img_size}
pixels_img_channels: 3
seed: ${seed}
avg_episode_length: ${default:${fixed_episode_length}, 10}
is_fixed_episode_length: ${is_not_none:${fixed_episode_length}}
max_episode_length: null
modality: ${modality}
dataset_seed: 1234
dataset_n_episodes: 10
dataset_next_observations_are_available: false
state_depends_on_action: true
reward_depends_on_action: true