id: ${generate_id:${setup.description},${setup.git.issue_id},${seed}}
description: Dummy
script_id: dummy
tags:
# - sample
git:
  commit_id: ${git_commit_id:}
  has_uncommitted_changes: ${git_has_uncommitted_changes:}
  issue_id: dummy
timestamp: ${date:}
viz:
  params:
notes:
parent_script_id:
slurm:
  id: ${slurm_id:}
  cloud: fair