scheme:
  _target_: algorithm.goal_relabeling.GoalMixture
  # `_node_cfg_` is a custom flag (see `utils.instantiate()`).
  _node_cfg_: null
  # Either "hard" (select one scheme among `schemes`) or "soft" (use a weighted sum
  # of each scheme's goal).
  mode: hard
  seed: ${seed}
  # `schemes` and `weights` must be defined on the comand-line, e.g. with:
  #   +replay_goal_relabeling@replay_goal_relabeling.scheme.schemes.decoded_encoded_t_plus_k_z_worker=decoded_encoded_t_plus_k_z_worker
  #   +replay_goal_relabeling@replay_goal_relabeling.scheme.schemes.t_plus_k_z_worker=t_plus_k_z_worker
  #   replay_goal_relabeling.scheme.weights={t_plus_k_z_worker: 0.3, decoded_encoded_t_plus_k_z_worker: 0.7}
  schemes: null
  weights: null

# Obtain the goal dimension and reward space from the first scheme.
goal_dim: ${._first_scheme.goal_dim}
reward_space: ${._first_scheme.reward_space}

_schemes_list: ${oc.dict.values:.scheme.schemes}
_first_scheme: ${._schemes_list[0]}