scheme:
  _target_: algorithm.goal_relabeling.t_plus_k_z_worker
  # Note that `k` may be either an integer or a pair [k_min, k_max].
  # In the latter case we sample uniformly from this range.
  k: ${hierarchy.manager.time_interval}
  seed: ${seed}
  # Whether the goal should be the difference between the encoding of the observation
  # at time `t+k` and the one at time `t`.
  delta: false

goal_dim: ${latent_dim}
reward_space: worker